import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Code Shiksa ",
  description: "Code Shiksa is a platform for MCA, BCA, and B.Tech students to explore final year projects in Web Development, AI, Digital Marketing, and more. Get access to training, internships, and real-world services in FullStack, DevOps, AWS, Graphic Design, Digital Marketing, and Video Editing.",
  keywords: [
    "Final Year Projects",
    "BCA Projects",
    "MCA Projects",
    "Computer Science Projects",
    "BCA Final Year Projects",
    "MCA Final Year Projects",
    "Post Graduation Final Year Projects",
    "Graduation Final Year Projects",
    "Web Development Course",
    "Full Stack Course",
    "Digital Marketing Course",
    "Video Editing Course",
    "Graphic Designing Course",
    "React Course",
    "Next Js Course",
    "JavaScript Course",
    "AWS Course",
    "Devops Course",
    "AI Course",
    "SEO Marketing",
    "Web Development Training and Internship",
    "Full Stack Training and Internship",
    "Digital Marketing Training and Internship",
    "Video Editing Training and Internship",
    "Graphic Designing Training and Internship",
    "React Training and Internship",
    "Next Js Training and Internship",
    "JavaScript Training and Internship",
    "AWS Training and Internship",
    "DevOps Training",
    "Internship Program",
    "Website Development",
    "Automation Services",

  ],
  openGraph: {
    title: "Code Shiksa | Projects, Internships & Training in Web Dev, DevOps, AI",
    description: "Join Code Shiksa for top-notch Final Year Projects, internships, and courses in Web Development, DevOps, Digital Marketing, and AI.",
    url: "https://yourwebsite.com",
    siteName: "Code Shiksa",
    images: [
      {
        url: "https://yourwebsite.com/og-image.jpg",
        width: 1200,
        height: 630,
        alt: "Code Shiksa Website Preview",
      },
    ],
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "Code Shiksa | Projects, Internships & Training in Web Dev, DevOps, AWS, AI and Digital Marketing",
    description: "Get industry-ready with Final Year Projects, career-boosting training in tech, Web Development, DevOps, Digital Marketing, Graphic Designing, and AI courses at Code Shiksa.",
    images: ["https://yourwebsite.com/twitter-image.jpg"],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="relative z-20">
          <Navbar />
        </div>
        {children}
      </body>
    </html>
  );
}

// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import Navbar from "@/components/navbar";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Code Shiksa",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         <div className="relative z-20">
//         <Navbar />
//         </div>
//         {children}
//       </body>
//     </html>
//   );
// }